### ISSUE TITLE
2D matching pipe line

### ISSUE THREAD

**Issue by KrzysztofZurad** [ethz-asl/libpointmatcher#265]
I've been struggling a bit to make libpointmatcher work with 2D case. My current setup:

I have a 3D point cloud projected to 2D (z axis = 0 for every point, because of specificity of my application a 2D projection seems reasonable).
I would like to calculate normal vectors and use shadow filter to eliminate outliers, however it seems to be impossible. Setting up z axis of each point to 0 gives me normal vectors all pointing up.
I would like to achieve normal vector calculation only for 2D case. I've tried several solutions, without sucess.

I've used a pmicp executable **with the same reference and reading point clouds**, for the sake of simplicity.

Option 1:
I've added an extra DataPointsFilter that removes 3'rd dimension from the data structure, however when I visualize output in ParaView I get such results:

for reference cloud:
![referencecloud](https://user-images.githubusercontent.com/29045552/42821671-60e5544a-89d9-11e8-869e-ddba9cc50c53.png)

Which seems to be all fine, however for the reading cloud I get:

![readingcloud](https://user-images.githubusercontent.com/29045552/42821712-7c4e7068-89d9-11e8-839c-7d9f54abb1ea.png)

As you can see it has been transformed in very weird way, that I don't understand at all.

Option 2:
I've manually removed z axis point from the input file, leaving only x and y component. I got

reference cloud:
![manualreferencecloud](https://user-images.githubusercontent.com/29045552/42822163-9c1ca878-89da-11e8-9288-47905e1330aa.png)

reading cloud:
![manualreadingcloud](https://user-images.githubusercontent.com/29045552/42822173-a54e22aa-89da-11e8-8b5b-557ff445ccd4.png)

My pipeline config files has been setup to:

```yaml
readingDataPointsFilters:
 - ProjectOrthoDataPointsFilter
 - SimpleSensorNoiseDataPointsFilter
 - SurfaceNormalDataPointsFilter:
     knn: 5
     keepNormals: 1
     keepDensities: 1
 #- MaxDensityDataPointsFilter:
 #    maxDensity: 10000
 - ObservationDirectionDataPointsFilter
 - OrientNormalsDataPointsFilter


referenceDataPointsFilters:
 - ProjectOrthoDataPointsFilter
 - SimpleSensorNoiseDataPointsFilter
 - SurfaceNormalDataPointsFilter:
     knn: 5
     keepNormals: 1
     keepDensities: 1
 #- MaxDensityDataPointsFilter:
 #    maxDensity: 10000
 - ObservationDirectionDataPointsFilter
 - OrientNormalsDataPointsFilter



matcher:
 KDTreeMatcher

outlierFilters:
   - NullOutlierFilter

errorMinimizer:
   IdentityErrorMinimizer

transformationCheckers:
   - CounterTransformationChecker

inspector:
  VTKFileInspector:
     baseFileName : vissteps
     dumpDataLinks : 1
     dumpReading : 1
     dumpReference : 1

logger:
  FileLogger

```
where ProjectOrthoDataPointsFilter is filter that I have tried to implement that simply removes a 3rd dimention from the point cloud.

```cpp
// ProjectOrthoDataPointsFilter
// Constructor
template<typename T>
DataPointsFiltersImpl<T>::ProjectOrthoDataPointsFilter::ProjectOrthoDataPointsFilter(const Parameters& params):
	DataPointsFilter("ProjectOrthoDataPointsFilter", ProjectOrthoDataPointsFilter::availableParameters(), params),
	zPlane(Parametrizable::get<T>("zPlane"))
{
    LOG_INFO_STREAM("Using ProjectOrthoDataPointsFilter with zPlane=" << zPlane);
}

// Compute
template<typename T>
typename PointMatcher<T>::DataPoints DataPointsFiltersImpl<T>::ProjectOrthoDataPointsFilter::filter(
	const DataPoints& input)
{
	DataPoints output(input);
	inPlaceFilter(output);
	return output;
}

// In-place filter
template<typename T>
void DataPointsFiltersImpl<T>::ProjectOrthoDataPointsFilter::inPlaceFilter(
	DataPoints& cloud)
{
    const int nbPointsIn = cloud.features.cols();
    typedef PointMatcher<T> PM;
    typedef typename PM::DataPoints DataPoints;
    typedef typename DataPoints::Label Label;
    typedef typename DataPoints::Labels Labels;

    Labels featLabels;
    featLabels.push_back(Label("x", 1));
    featLabels.push_back(Label("y", 1));
    featLabels.push_back(Label("pad", 1));

    Labels descLabels;

    DataPoints cloud_filtered(featLabels, descLabels, nbPointsIn);
    // cloud_filtered.getFeatureViewByName("pad")

    int j = 0;
    for (int i = 0; i < nbPointsIn; i++)
    {
        cloud_filtered.features(0, i) = cloud.features.col(i).array()[0];
        cloud_filtered.features(1, i) = cloud.features.col(i).array()[1];
        cloud_filtered.features(2, i) = 1;
        j++;
    }



    // cloud = cloud_filtered;
    PointMatcher<T>::swapDataPoints(cloud, cloud_filtered);

    // for (int i = 0; i < nbPointsIn; i++)
    // {
    //     std::cout << "Cloud " << cloud.features.col(i).array() << std::endl;
    //     std::cout << "Cloud_filtered " << cloud_filtered.features.col(i).array() << std::endl;
    // }

    // cloud.conservativeResize(j);
}

template struct DataPointsFiltersImpl<float>::ProjectOrthoDataPointsFilter;
template struct DataPointsFiltersImpl<double>::ProjectOrthoDataPointsFilter;
```

am I missing something here? How should I setup a 2D processing pipeline to correctly filter and scan match my input?

Since I couldn't find many examples of libpointmatcher in 2D, I've been wondering what should be the proper processing pipeline setup.
