### ISSUE TITLE
Using libpointmatcher for 2D lidars extrinsic calibration 

### ISSUE THREAD

**Issue by artemiialessandrini** [ethz-asl/libpointmatcher#368]

**Comment by simonpierredeschenes** [comment]
I am not sure to understand what the problem is, do you get an output translation of 0 ([0, 0, 0]^T)? If you add a VTKFileInspector inspector to your yaml configuration file, libpointmatcher will save the reading point cloud at each iteration. Then, you will be able to see what is happening when the clouds are matched. The inspector configuration looks like this : 
```
VTKFileInspector:
    baseFileName: SOME_OUTPUT_PATH
    dumpReading: 1
    dumpReference: 1
    writeBinary: 1
```
If you cannot find the issue with the inspector, it would help if you could provide an example cloud to help us reproduce the issue on our side.
