### ISSUE TITLE
Meaning of maxRotationNorm in BoundTransformationChecker

### ISSUE THREAD

**Issue by dasisttao** [ethz-asl/libpointmatcher#476]
Hallo, again! In transformationCheckers there's a BoundTransformationChecker. The parameter is listed like below.

```
transformationCheckers:
  - BoundTransformationChecker:
      maxRotationNorm: 0.80
      maxTranslationNorm: 5.00
```

I would like to ask what's the meanig of Norm here. And the Metric of these parameters is in radius or meter, is that right?

Thanks!
