### ISSUE TITLE
how to improve icp resolution 

### ISSUE THREAD

**Issue by dbdxnuliba** [ethz-asl/libpointmatcher#504]
1)this is the icp result :
![image](https://user-images.githubusercontent.com/13350158/206358697-a8d10df6-2420-48aa-9f42-b72538e92d66.png)
![image](https://user-images.githubusercontent.com/13350158/206359774-7b27fc2a-6f41-4649-b2e2-ed28a4711db7.png)

![image](https://user-images.githubusercontent.com/13350158/206359176-ec96d4cb-96ac-42a7-aa85-dd4d3a38a1e4.png)

in the fig:
white cloud :template cloud pt
blue cloud:reading in cloud pt
read cloud: after icp processing cloud pt
2)
I got the result by :
rosrun libpointmatcher pmicp -v --config src/build_depend/libpointmatcher-master/examples/icp_tutorial/icp_tutorial_cfg_body.yaml output/child_body.ply  output/raw_in_base_footprint.ply 

3)
icp_tutorial_cfg_body.yaml  is as the follwing:
```
readingDataPointsFilters:
  - SurfaceNormalDataPointsFilter:
        knn: 10
        keepDensities: 1

  - MaxDensityDataPointsFilter:
       maxDensity: 0.3

referenceDataPointsFilters:
  - SurfaceNormalDataPointsFilter:
      knn: 10

matcher:
  KDTreeMatcher:
    knn: 1
    epsilon: 0.0

outlierFilters:
  - TrimmedDistOutlierFilter:
      ratio: 0.75

errorMinimizer:
  PointToPlaneErrorMinimizer

transformationCheckers:
  - CounterTransformationChecker:
      maxIterationCount: 40
  - DifferentialTransformationChecker:
      minDiffRotErr: 0.001
      minDiffTransErr: 0.01
      smoothLength: 4   
      
inspector:
  NullInspector
#  VTKFileInspector

logger:
  NullLogger
#  FileLogger


```
4)
the template ply file is as follows:
[template.zip](https://github.com/ethz-asl/libpointmatcher/files/10182193/template.zip)

the reading data ply file:

[reading_data.zip](https://github.com/ethz-asl/libpointmatcher/files/10182195/reading_data.zip)

Question：
we can see in the above result figure,the point_cloud was not matched well,
how can we improve the matching result.
Any helps is pleasured!
